using Sagant.Effects;

namespace Sagant.Protocol;

/// <summary>
/// The single canonical durable representation of a parent/child workflow link — persisted by both
/// sides: the parent holds a list of these (one per child it has ever started, across every group,
/// lifetime-scoped — see <see cref="WorkflowRuntimeState{TState}.Children"/>), the child holds
/// exactly one (it has at most one parent — see <see cref="WorkflowRuntimeState{TState}.ParentRelationship"/>).
/// Nothing about a parent/child relationship is tracked anywhere else — no separate lifetime ledger,
/// no member list duplicated onto group state.
/// </summary>
/// <param name="RelationshipId">
/// Deterministic, derived once at first-persist as <c>$"{ParentWorkflowId}:{GroupId}:{ChildWorkflowId}"</c>
/// — never regenerated on retry/recovery. Doubles as the idempotency key for the child's start
/// command, which is what makes redelivering it arbitrarily many times safe.
/// </param>
/// <param name="GroupId">
/// Which <c>ChildGroupState</c> this relationship belongs to. Framework-generated by default,
/// explicit only if the workflow author asked for a named group.
/// </param>
/// <param name="Generation">
/// The owning group's generation at the moment this relationship was created — compared against the
/// group's *current* generation to detect a stale lifecycle notification (one raised before the
/// group finalized/moved on) versus one that's still relevant. Same role <c>_stepEpoch</c> plays for
/// a single step's retry attempts, one level up.
/// </param>
/// <param name="Result">
/// The child's final <c>TState</c> once <see cref="ChildStatus.Completed"/> — <c>object</c>-typed,
/// persisted and round-tripped exactly like every other polymorphic field this engine already
/// persists (<c>Transition.StepTransition.Input</c>, <c>CurrentStepInput</c>). <c>null</c> for any
/// other status.
/// </param>
/// <param name="TraceParent">
/// The parent's own trace context at the moment it started this child, handed to the child on its
/// own <c>WorkflowEnvelope.ParentRelationship</c> — the source for the child's first activity
/// linking back to the parent. Set once, at start; never updated afterward.
/// </param>
/// <param name="ResultTraceParent">
/// The reporting child's own trace context at the moment it sent its terminal
/// <c>ChildLifecycleNotification</c> — <c>null</c> until that notification arrives (and for any
/// straggler that never reports). The opposite direction from <see cref="TraceParent"/> (the
/// parent's context handed to the child at start): same relationship, kept as a separate field so
/// neither ever silently overwrites the other's meaning. Source for the <c>ActivityLink</c>s a
/// group's <c>ResumeAt</c> step activity carries back to every member's own final trace.
/// </param>
public sealed record ChildWorkflowRelationship(
    string RelationshipId,
    string ParentWorkflowType,
    string ParentWorkflowId,
    string ChildWorkflowType,
    string ChildWorkflowId,
    string GroupId,
    int Generation,
    ChildStatus Status,
    object? Result,
    WorkflowFailure? Failure,
    string? TraceParent,
    ParentClosePolicy ParentClosePolicy,
    /// <summary>
    /// The original command this child was started with — kept for the relationship's entire
    /// persisted lifetime. Redelivery correctness only depends on this field existing whenever the
    /// relationship's <c>Status</c> is still <see cref="ChildStatus.Pending"/>; keeping it beyond
    /// that costs a few extra persisted bytes per relationship, cheap relative to the guarantee it
    /// buys. <c>object</c>-typed, persisted exactly like every other polymorphic field this engine
    /// already persists (<c>CurrentStepInput</c>, <c>Transition.StepTransition.Input</c>).
    /// </summary>
    object Command,
    string? ResultTraceParent = null);
